### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by tyradeveloper** [mattbrailsford/umbraco-headrest#11]
I am trying to make headrest work with our umbraco v8 solution. Its giving some errors when i run it. I am trying to map only homepage for only one property ColorTheme. The exception is:

{"Exception has been thrown by the target of an invocation."} | System.Reflection.TargetInvocationException
InnerException | {"Don't know how to map Umbraco.Web.PublishedModels.Home to demo.headrestv8.ViewModels.HomePageViewModel."} | System.Exception {System.InvalidOperationException}

the exception is thrown in HeadrestOptions class on line 47 where mapFunc.Invoke is executed.

when i look deeper into the exception. Under TargetSite-declaringMethod

'((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)($exception).TargetSite).DeclaringType).DeclaringMethod' threw an exception of type 'System.InvalidOperationException'
Message: "Method may only be called on a Type for which Type.IsGenericParameter is true."

Its same problem with GenericParameterAttributes and GenericParameterPosition.

Any ideas what could be wrong?

regards,
Qaisar

**Comment by mattbrailsford** [comment]
HI @tyradeveloper 

Could you share your Headrest configuration please so I can understand what your mappings look like?

Many thanks

Matt

**Comment by tyradeveloper** [comment]
Hi Matt

Thank you for answering.
I am trying to map only one property ColorTheme from the Home model to HomePageViewModel. I have reused most of your code from nullorwhitespace backend. Following is the configuration of Headrest.

````csharp
namespace demo.headrestv8.Composing
{
    public class DemoHeadrestComponent:IComponent
    {
        private readonly HeadRest _headRest;

        public DemoHeadrestComponent(HeadRest headRest)
            => _headRest = headRest;

        public void Initialize()
        {
            _headRest.ConfigureEndpoint(new HeadRestOptions
            {
                ViewModelMappings = new HeadRestViewModelMap()
            .For(Home.ModelTypeAlias).MapTo<HomePageViewModel>()
            });
            
        }

        public void Terminate()
        { }
    }
}


namespace demo.headrestv8.Composing
{
    [ComposeAfter(typeof(HeadRestComposer))]
    public class DemoHeadrestComposer:IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components()
                .Append<DemoHeadrestComponent>();

            composition.WithCollectionBuilder<MapDefinitionCollectionBuilder>()
                .Add<HeadrestMapDefinition>();
        }
    }
}

namespace demo.headrestv8.Mapping.Maps
{
    public abstract class BaseMapping<TSelf, TFrom, TTo>
        where TSelf : BaseMapping<TSelf, TFrom, TTo>, new()
        where TTo : new()
    {
        private static readonly Lazy<TSelf> lazy = new Lazy<TSelf>(() => new TSelf());

        public static TSelf Instance { get { return lazy.Value; } }

        protected BaseMapping()
        { }

        public TTo Map(TFrom src, MapperContext ctx)
        {
            var dst = new TTo();
            Map(src, dst, ctx);
            return dst;
        }

        public abstract void Map(TFrom src, TTo dst, MapperContext ctx);
    }
}

namespace demo.headrestv8.Mapping.Maps
{
    public class BaseViewModelMapping : BaseMapping<BaseViewModelMapping, Home, BaseViewModel>
    {
        public override void Map(Home src, BaseViewModel dst, MapperContext ctx)
    {           

    }
}
}
namespace demo.headrestv8.Mapping.Maps
{
    public class HomeViewModelMapping : BaseMapping<HomeViewModelMapping, Home, HomePageViewModel>
    {
        public override void Map(Home src, HomePageViewModel dst, MapperContext ctx)
        {
            // Base mappings
            BaseViewModelMapping.Instance.Map(src, dst, ctx);

            // Custom maps
            dst.ColorTheme = src.ColorTheme;
        }
    }
}

namespace demo.headrestv8.Mapping
{
    public class HeadrestMapDefinition : IMapDefinition
    {
        public void DefineMaps(UmbracoMapper mapper)
        {
            mapper.Define<Home, HomePageViewModel>(HomeViewModelMapping.Instance.Map);
        }
    }
}

namespace demo.headrestv8.Mapping.Maps
{
    public static class UmbracoMapperExtensions
    {
        public static void Define<TFrom, TTo>(this UmbracoMapper mapper, Action<TFrom, TTo, MapperContext> map)
            where TTo : new()
        {
            mapper.Define(
               (src, ctx) => new TTo(),
               map
            );
        }
    }
}

namespace demo.headrestv8.ViewModels
{
    public class BaseViewModel
    {
       
    }
}

namespace demo.headrestv8.ViewModels
{
    public class HomePageViewModel:BaseViewModel
    {
        public string ColorTheme { get; set; }
    }
}
````

regards,
Qaisar

**Comment by mattbrailsford** [comment]
Hmm, it looks ok to me. 

It's possible you might be hitting a problem I came across here https://github.com/umbraco/Umbraco-CMS/issues/6255 The built in Umbraco mapper has an issue that makes it forget maps, which I've submitted a fix for (due in 8.1.5) and for which in my nullorwhitespace project, I run Umbraco on a custom DLL because of it. Saying this however, your symptoms don't appear to be the same.

Failing this, the best I could suggest is to pull the source down and try debugging into it to see what the mapping is missing.

**Comment by tyradeveloper** [comment]
I am using umbraco 8.1.3 thats the version i could see in the Headrest references. Is this dll available somewhere i can download?

I also tried to debug Headrest code and it seems its failing at 

`return mapFunc.Invoke(Current.Mapper, new object[] { ctx.Content, ctxAction });`

in HeadrestOptions class constructer.

`public HeadRestOptions()
        {
            Mode = HeadRestEndpointMode.Dedicated;
            ControllerType = typeof(HeadRestController);
            Mapper = (ctx) => {

                // Currently have to call the UmbracoMapper.Map function
                // via reflection as there are no non-generic versions
                // available, and as we only know types at runtime, this
                // is the only way we can call them. We should keep an eye
                // on https://github.com/umbraco/Umbraco-CMS/issues/6250
                // and if this ever changes, we should switch to use the 
                // map methods instead
                var mapFunc = typeof(UmbracoMapper).GetMethods()
                    .First(m => m.Name == "Map" 
                        && m.GetGenericArguments().Count() == 1
                        && m.GetParameters()
                            .Select(p => p.ParameterType)
                            .SequenceEqual(new[] {
                                typeof(object),
                                typeof(Action<MapperContext>)
                            })
                    )
                    .MakeGenericMethod(ctx.ViewModelType);

                var ctxAction = new Action<MapperContext>(x => x.SetHeadRestMappingContext(ctx));

                return mapFunc.Invoke(Current.Mapper, new object[] { ctx.Content, ctxAction });

            };`

**Comment by mattbrailsford** [comment]
Yea, at that point you need to start debugging into Umbraco as it's the Umbraco mapper that has lost the mapping so you'd need to a) make sure your mapping is in there to start with and b) find out why it disappears.

I've zipped up my bin folder so you can try the Umbraco DLLs from there https://www.dropbox.com/s/2ci3ffopmz43cet/now_bin.zip?dl=0 but failing this, you'll need to debug into the Umbraco code and find out what's going on. Unfortunately the Umbraco Mapper isn't heavily battle tested yet so it still has some issues.

**Comment by tyradeveloper** [comment]
Thanks alot Matt, I will give it a try and will come back with the results :-)

Have a good weekend :-)

**Comment by tyradeveloper** [comment]
Hi Matts

It works now :-)
Actually the problem was that i was running it in PureLive mode for Umbraco Model builder. When i changed it to Dll mode, generated the models through Umbraco backend and referenced the dll in Visual studio. It worked without any problems.

Thank you very much for the help.

**Comment by bgilbert6** [comment]
Tried literally everything and couldn't get rid of this error. The document ion doesn't explain a lot about setup for Umbraco. It's not clear if you need to install the non embedded version of ModelsBuilder? This was from just a normal Umbraco installation, version 8.6.2. Tried all kinds of "ModelsMode" but none worked.

**Comment by mvanhelmont** [comment]
@bgilbert6 

have you made a MapDefinition for your viewmodel?

I also get this message and was forgotten to make one. When i created one everything works as expected. Thanks @mattbrailsford for this great package
