### ISSUE TITLE
How to build and install?

### ISSUE THREAD

**Issue by cdecinkoKnight** [mattbrailsford/umbraco-headrest#12]
None of the information I've found is providing me the correct information on how to build and install this as a local package.  How?

**Comment by mattbrailsford** [comment]
Hi @cdecinkoKnight 

You can download the source code, open the `Our.Umbraco.HeadRest.sln` file in the `src` folder, compile it for release, then copy the `Our.Umbraco.HeadRest.dll` from the `bin\Release` to your project bin folder.

You can also run the `build.cmd` file in the root, which will generate a nuget file in the `artifacts` folder, then you can install the nuget package as a local package file. See here for details on adding a local package src https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources
