### ISSUE TITLE
Self-referencing loop for nested IPublishedContent

### ISSUE THREAD

**Issue by acullenCNA** [mattbrailsford/umbraco-headrest#15]
I'm attempting to recreate the NullOrWhitespace demo using a local copy of Umbraco with the Starter Kit package. I've got most things sorted out, but it appears that any time I define a nested IPublishedContent property (i.e., set a photo on a person node, or select person records to add under "Featured People" on the people node), I run in to a self-referencing loop error. It appears to be an issue with the contentType property. Here is one such example, generated from the Matt Brailsford page (which seemed a logical choice). 

`{"department":["United Kingdom","mvp"],"email":"","facebookUsername":"","instagramUsername":"circuitbeard","linkedInUsername":"","twitterUsername":"mattbrailsford","photo":{"umbracoBytes":0,"umbracoExtension":"","umbracoFile":{"src":"/media/eee91c05b2e84031a056dcd7f28eff89/00000006000000000000000000000000/18531852339_981b067419_h.jpg","focalPoint":null,"crops":null},"umbracoHeight":0,"umbracoWidth":0,"contentType":{"id":1032,"alias":"Image","itemType":3,"compositionAliases":[],"variations":0,"propertyTypes":[{{"message":"Self referencing loop detected for property 'contentType' with type 'Umbraco.Core.Models.PublishedContent.PublishedContentType'. Path 'photo.contentType.propertyTypes[0]'."}`

**Comment by untiedshoes** [comment]
Hi,

I know this is a while ago now, but, did you manage to solve this as I'm having exactly the same issue, although with a grid inside nested content.

Regards,
Craig

**Comment by untiedshoes** [comment]
Never-mind, managed to sort it myself using [JsonIgnore].. e.g.

`[JsonIgnore]
public object homePageNestedComponents { get; set; }`

**Comment by untiedshoes** [comment]
Ignore that...

Doesn't work :(

**Comment by untiedshoes** [comment]
Just to add to this for anyone else looking for a solution?

I downloaded the source, and created my own CamelCasePropertyNamesContractResolver using some of leekelleher's / umbraco-contentment.

Code below:

`public sealed class PublishedContentContractResolver : CamelCasePropertyNamesContractResolver
    {
        public static readonly PublishedContentContractResolver Instance = new PublishedContentContractResolver();

        private readonly Dictionary<string, JsonConverter> _converterLookup;
        private readonly HashSet<string> _ignoreFromContent;
        private readonly HashSet<string> _ignoreFromProperty;
        private readonly HashSet<string> _ignoreFromType;

        public PublishedContentContractResolver()
        {
            _converterLookup = new Dictionary<string, JsonConverter>(StringComparer.OrdinalIgnoreCase)
            {
                { "ItemType", new StringEnumConverter()},
                { typeof(IHtmlString).FullName, new IHtmlStringConverter()},

            };

            _ignoreFromContent = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "CompositionAliases",
                "ContentSet",
                "PropertyTypes",
                "ObjectContent",
                "Properties",
                "Parent",
                "Children",
                "ChildrenForAllCultures",
                "DocumentTypeId",
                "WriterName",
                "CreatorName",
                "WriterId",
                "CreatorId",
                "CreateDate",
                "UpdateDate",
                "Version",
                "SortOrder",
                "TemplateId",
                "IsDraft",
                "ItemType",
                "ContentType",
                "Url",
                "ContentSet",
            };

            _ignoreFromProperty = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "PropertyType",
                "ReferenceCacheLevel",
            };

            _ignoreFromType = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "ContentType",
                "PropertyTypes",
            };

        }

        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var property = base.CreateProperty(member, memberSerialization);

            if (typeof(IPublishedContent).IsAssignableFrom(member.DeclaringType))
            {
                property.ShouldSerialize = _ =>
                {
                    return _ignoreFromContent.Contains(property.PropertyName) == false;
                };
            }
            else if (typeof(IPublishedProperty).IsAssignableFrom(member.DeclaringType))
            {
                property.ShouldSerialize = _ =>
                {
                    return _ignoreFromProperty.Contains(property.PropertyName) == false;
                };
            } 
            else if (typeof(IPublishedContentType).IsAssignableFrom(member.DeclaringType))
            {
                property.ShouldSerialize = _ =>
                {
                    return _ignoreFromType.Contains(property.PropertyName) == false;
                };
            }

            if (_converterLookup.ContainsKey(property.PropertyName))
            {
                property.Converter = _converterLookup[property.PropertyName];

            }
            else if (_converterLookup.ContainsKey(property.PropertyType.FullName))
            {

                property.Converter = _converterLookup[property.PropertyType.FullName];
            }

            return property;
        }
    }`

**Comment by NeilHodges** [comment]
Hi @untiedshoes I'm having the exact same problem, returning a Media Picker:

`{"mainLogo":{"umbracoBytes":19363,"umbracoExtension":"png","umbracoFile":{"src":"/media/elbfo2ui/k-medium.png","focalPoint":null,"crops":null},"umbracoHeight":710,"umbracoWidth":710,"contentType":{"id":1032,"alias":"Image","itemType":3,"compositionAliases":[],"variations":0,"propertyTypes":[{{"message":"Self referencing loop detected for property 'contentType' with type 'Umbraco.Core.Models.PublishedContent.PublishedContentType'. Path 'mainLogo.contentType.propertyTypes[0]'."}`

Am I right in thinking you downloaded the .sln and override the **CamelCasePropertyNamesContractResolver** 

Did this work Ok in most instances? 

I couldn't find a reference to IHtmlStringConverter?

**Comment by untiedshoes** [comment]
> Hi @untiedshoes I'm having the exact same problem, returning a Media Picker:
> 
> `{"mainLogo":{"umbracoBytes":19363,"umbracoExtension":"png","umbracoFile":{"src":"/media/elbfo2ui/k-medium.png","focalPoint":null,"crops":null},"umbracoHeight":710,"umbracoWidth":710,"contentType":{"id":1032,"alias":"Image","itemType":3,"compositionAliases":[],"variations":0,"propertyTypes":[{{"message":"Self referencing loop detected for property 'contentType' with type 'Umbraco.Core.Models.PublishedContent.PublishedContentType'. Path 'mainLogo.contentType.propertyTypes[0]'."}`
> 
> Am I right in thinking you downloaded the .sln and override the **CamelCasePropertyNamesContractResolver**
> 
> Did this work Ok in most instances?
> 
> I couldn't find a reference to IHtmlStringConverter?

Hi Neil,

Yep, that's exactly what I did. So far the only issue I've had was with using the skybrud.umbraco.griddata.griddatamodel - which I've had to ditch as I've not had a reply about the issue as yet.

If you download the source, then create a new Helper..

`public class IHtmlStringConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return typeof(IHtmlString).IsAssignableFrom(objectType);
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            IHtmlString source = value as IHtmlString;
            if (source == null)
            {
                return;
            }

            writer.WriteValue(source.ToString());
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            // warning, not thoroughly tested
            var html = reader.Value as string;
            return html == null ? null : System.Web.Mvc.MvcHtmlString.Create(html);
        }
    }`

And then, for Serialization, create a new class.

`public sealed class PublishedContentContractResolver : CamelCasePropertyNamesContractResolver
    {
        public static readonly PublishedContentContractResolver Instance = new PublishedContentContractResolver();

        private readonly Dictionary<string, JsonConverter> _converterLookup;
        private readonly HashSet<string> _ignoreFromContent;
        private readonly HashSet<string> _ignoreFromProperty;
        private readonly HashSet<string> _ignoreFromType;

        public PublishedContentContractResolver()
        {
            _converterLookup = new Dictionary<string, JsonConverter>(StringComparer.OrdinalIgnoreCase)
            {
                { "ItemType", new StringEnumConverter()},
                { typeof(IHtmlString).FullName, new IHtmlStringConverter()},

            };

            _ignoreFromContent = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "CompositionAliases",
                "ContentSet",
                "PropertyTypes",
                "ObjectContent",
                "Properties",
                "Parent",
                "Children",
                "ChildrenForAllCultures",
                "DocumentTypeId",
                "WriterName",
                "CreatorName",
                "WriterId",
                "CreatorId",
                "CreateDate",
                "UpdateDate",
                "Version",
                "SortOrder",
                "TemplateId",
                "IsDraft",
                "ItemType",
                "ContentType",
                "Url",
                "ContentSet",
            };

            _ignoreFromProperty = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "PropertyType",
                "ReferenceCacheLevel",
            };

            _ignoreFromType = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "ContentType",
                "PropertyTypes",
            };

        }

        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var property = base.CreateProperty(member, memberSerialization);

            if (typeof(IPublishedContent).IsAssignableFrom(member.DeclaringType))
            {
                property.ShouldSerialize = _ =>
                {
                    return _ignoreFromContent.Contains(property.PropertyName) == false;
                };
            }
            else if (typeof(IPublishedProperty).IsAssignableFrom(member.DeclaringType))
            {
                property.ShouldSerialize = _ =>
                {
                    return _ignoreFromProperty.Contains(property.PropertyName) == false;
                };
            } 
            else if (typeof(IPublishedContentType).IsAssignableFrom(member.DeclaringType))
            {
                property.ShouldSerialize = _ =>
                {
                    return _ignoreFromType.Contains(property.PropertyName) == false;
                };
            }

            if (_converterLookup.ContainsKey(property.PropertyName))
            {
                property.Converter = _converterLookup[property.PropertyName];

            }
            else if (_converterLookup.ContainsKey(property.PropertyType.FullName))
            {

                property.Converter = _converterLookup[property.PropertyType.FullName];
            }

            return property;
        }
    }`

And use that, rather than the default one used in HeadrestResult.cs

Let me know how you get on?

Craig

**Comment by NeilHodges** [comment]
@untiedshoes worked a charm! Thanks!

@mattbrailsford This works well, would this be Ok for PR?

**Comment by untiedshoes** [comment]
> @untiedshoes worked a charm! Thanks!
> 
> @mattbrailsford This works well, would this be Ok for PR?

Excellent, glad it worked out for you :)

I actually stopped using the project as I was having problems with pulling Children (it really could do with a very simple example of how to pull children) and went with my own API. I still had to use the custom Contract Resolver though.

I know @mattbrailsford has the nullorwhitespace project using the headrest project, but there's so much going on, it's difficult to go through.

Craig

**Comment by NeilHodges** [comment]
@untiedshoes ah yes, I've usually done the same, rolled my own API, but hit the dreaded - 
**Self-referencing loop detected for property 'contentType'** before doing that. 

I thought I'll use HeadRest this time around as Matt's probably sorted that one :)

Thanks for the help though on that, I was gutted when I hit that error again.

I think to output the Children you create an `IEnumberable <IPublishedContent>` within the View Model and it should automap the Children? Although I've not got round to that part yet, I will know more today.

I did find this good project on GitHub with some good examples - https://github.com/mzajkowski/umbraco-headless-playground seems to be a good referencing point, it doesn't go into major detail with property types and such but found it a good starting point with examples.

**Comment by untiedshoes** [comment]
@NeilHodges Yeah, I'd found that too, but until umbraco finalises the content blocks, I didn't want to delve into the headless project.

I'm just faffing at the moment for an up and coming project (on hold at the moment due to the current predicament we all find ourselves in lol).

**Comment by mattbrailsford** [comment]
Just had a quick look here and I think your main issue is you aren't converting your nested models to view models like you should be. You shouldn't really be sending `IPublishedContent` through your APIs, instead, you should be mapping them to view models so that you only send down the wire **exactly** what you need on the front end.

You can see an example in the NullOrWhitespace project of how I map child items https://github.com/mattbrailsford/nullorwhitespace-backend/blob/master/NullOrWhitespace/Web/Mapping/Maps/BasicNodeViewModelMapper.cs#L15 Here, I call the map function recursively, mapping itself and all it's children to a `BasicNodeViewModel` view model. At no point do I send a raw `IPublishedContent` entity, and neither should you.

Just so you know, Headrest doesn't auto map anything. It's completely down to you to perform all mapping operations. All headrest does is map a URL to a map operation of your creation.

**Comment by mattbrailsford** [comment]
Closing this issue. Resolution is don't send `IPublishedContent` through your APIs, instead, map them to view models in your own map operation.
