### ISSUE TITLE
Is this project still alive

### ISSUE THREAD

**Issue by MagicMetaMike** [mattbrailsford/umbraco-headrest#22]
There seems to be little activity, is this project still valid and able to work on Umbraco 8.9 +?

**Comment by biapar** [comment]
+1

**Comment by mattbrailsford** [comment]
Not doing a lot on the project, but it already supports v8. The PR was merged in here https://github.com/mattbrailsford/umbraco-headrest/pull/10 and the v1.0.0 release states it's v8 only https://github.com/mattbrailsford/umbraco-headrest/releases

**Comment by biapar** [comment]
Will be support for v9?

**Comment by mattbrailsford** [comment]
Nothing planned yet. 

I'm open to PR's though if anyone wants to take a look.

**Comment by biapar** [comment]
I have not tried yet the v9 version but I can image that will be a lots changes.
